using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace Equipment_Manager
{
    /// <summary>
    /// Interaction logic for AddMaintainanceReport.xaml
    /// </summary>
    public partial class AddMaintainanceReport : Window
    {
        public AddMaintainanceReport()
        {
            InitializeComponent();

            //  maintainance_reports.ItemsSource = values.AsDataView();
            ExcelFileSelector fileS = new ExcelFileSelector();
            fileS.ShowDialog();
            try
            {
                DataTable values = DBManager.SelectFromExcel(fileS.fileName, fileS.sheetName, fileS.cellValues);

                maintainance_reports.ItemsSource = values.AsDataView();
            }
            catch(Exception ex)
            {

            }

        }

        private void maintainance_reports_AutoGeneratedColumns(object sender, EventArgs e)
        {
            try
            {
                maintainance_reports.Columns[1].Header = "Name";
                maintainance_reports.Columns[0].Header = "id";
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error Occured", "Invalid Data size", MessageBoxButton.OK, MessageBoxImage.Error);
                this.Close();
            }
    }

        private void insertButton_Click(object sender, RoutedEventArgs e)
        {

        }
    }
}
