using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace Equipment_Manager
{
    /// <summary>
    /// Interaction logic for NewInsurancePayment.xaml
    /// </summary>
    public partial class NewInsurancePayment : Window
    {
        DataTable values;
        public NewInsurancePayment()
        {
            InitializeComponent();
            try
            {

                //  insurance_payments.ItemsSource = values.AsDataView();
                ExcelFileSelector fileS = new ExcelFileSelector();
                fileS.ShowDialog();
                values = DBManager.SelectFromExcel(fileS.fileName, fileS.sheetName, fileS.cellValues);

                insurance_payments.ItemsSource = values.AsDataView();
            }
            catch
            {

            }

        }

        private void insurance_payments_AutoGeneratedColumns(object sender, EventArgs e)
        {
            try
            {


                insurance_payments.Columns[0].Header = "Equipment ID";
                insurance_payments.Columns[1].Header = "Value Payed";
                insurance_payments.Columns[2].Header = "Payment Date";
             


            }
            catch (Exception ex)
            {

                //this.Close();

            }
        }

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            if (values == null || values.Columns.Count != 3)
            {
                this.Close();
                myMessageBox mm = new myMessageBox("Column Count Doesnt match or no data found", "Error", "OK", 1);
                mm.ShowDialog();

                //  MessageBox.Show("Invalid Data size", "Error Occured", MessageBoxButton.OK, MessageBoxImage.Error);

            }
        }

        private void insertButton_Click(object sender, RoutedEventArgs e)
        {
            int i = 0;
            string datas = "";
            try
            {
                foreach (DataRow row in values.Rows)
                {
                    if (i == 0)
                    {
                        datas = "('" + row[0].ToString() + "','" + row[1].ToString() + "','" + Convert.ToDateTime(row[2].ToString()).ToString("yyyy-MM-dd HH:mm:ss") + "')";

                    }
                    else
                    {
                        datas = datas + ",('" + row[0].ToString() + "','" + row[1].ToString() + "','" +Convert.ToDateTime(row[2].ToString()).ToString("yyyy-MM-dd HH:mm:ss") + "')";
                    }
                    i++;
                }
                string res = DBManager.InsertIntoInsuranceDetails(datas);
                if (!res.Contains("Success"))
                {
                    myMessageBox mm = new myMessageBox("Invalid Data Type Found. Check your data again", "Error", "OK", 1);
                    mm.ShowDialog();

                   // MessageBox.Show("Invalid Data Type Found. Check your data again", "Error Occured", MessageBoxButton.OK, MessageBoxImage.Error);

                }
                else
                {
                    myMessageBox mm = new myMessageBox("Data Added Successfully", "Success", "OK", 0);
                    mm.ShowDialog();

                    //MessageBox.Show("Data Added Succesfully", "Successfully Added", MessageBoxButton.OK, MessageBoxImage.Information);
                    this.Close();
                }
            }
            catch (Exception ex)
            {
                //
            }
        }

    }
}

