using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace Equipment_Manager
{
    /// <summary>
    /// Interaction logic for NewServiceRequest.xaml
    /// </summary>
    public partial class NewServiceRequest : Window
    {
        DataTable values;
        public NewServiceRequest()
        {
            InitializeComponent();
            try
            {

                //  maintainance_request.ItemsSource = values.AsDataView();
                ExcelFileSelector fileS = new ExcelFileSelector();
                fileS.ShowDialog();
                values = DBManager.SelectFromExcel(fileS.fileName, fileS.sheetName, fileS.cellValues);

                service_request.ItemsSource = values.AsDataView();
            }
            catch (Exception ex)
            {

            }
        }

        private void service_request_AutoGeneratedColumns(object sender, EventArgs e)
        {
            try
            {


                service_request.Columns[0].Header = "Equipment ID";
                service_request.Columns[1].Header = "Requested Date";
                service_request.Columns[2].Header = "Requested By";
                



            }
            catch (Exception ex)
            {

                //this.Close();

            }
        }

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            if (values == null || values.Columns.Count != 3)
            {
                this.Close();
                myMessageBox mm = new myMessageBox("Column Count Doesnt match or no data found", "Error", "OK", 1);
                mm.ShowDialog();

               // MessageBox.Show("Invalid Data size", "Error Occured", MessageBoxButton.OK, MessageBoxImage.Error);

            }
        }

        private void insertButton_Click(object sender, RoutedEventArgs e)
        {
            int i = 0;
            string datas = "";
            string updateQueries = "";
            try
            {
                foreach (DataRow row in values.Rows)
                {
                    if (i == 0)
                    {
                        datas = "('" + row[0].ToString() + "','" + Convert.ToDateTime(row[1].ToString()).ToString("yyyy-MM-dd HH:mm:ss") + "','"+ row[2].ToString() + "')";

                    }
                    else
                    {
                        datas = datas + ",('" + row[0].ToString() + "','" + Convert.ToDateTime(row[1].ToString()).ToString("yyyy-MM-dd HH:mm:ss") +  "','" + row[2].ToString()  + "')";
                    }
                    updateQueries += "UPDATE equipment_list SET equipment_list.current_status = '7' WHERE equipment_list.equipment_id = '" + row[0].ToString() + "';\n";
                    i++;
                }
                string res = DBManager.InsertIntoServiceRequest(datas);
                if (!res.Contains("Success"))
                {
                    myMessageBox mm = new myMessageBox("Invalid Data Found. Check your Data!", "Error", "OK", 1);
                    mm.ShowDialog();

                   // MessageBox.Show("Invalid Data Type Found. Check your data again", "Error Occured", MessageBoxButton.OK, MessageBoxImage.Error);

                }
                else
                {
                    DBManager.UpdateDatabaseQuery(updateQueries);
                    myMessageBox mm = new myMessageBox("Data Added Succefully", "Success", "OK", 0);
                    mm.ShowDialog();

                    // MessageBox.Show("Data Added Succesfully", "Successfully Added", MessageBoxButton.OK, MessageBoxImage.Information);
                    this.Close();
                }
            }
            catch (Exception ex)
            {
                //
            }
        }

    }
}