using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace Equipment_Manager
{
    /// <summary>
    /// Interaction logic for PurchaseRequest.xaml
    /// </summary>
    public partial class PurchaseRequest : Window
    {
        DataTable values;
        public PurchaseRequest()
        {
           
            InitializeComponent();
            try
            {

                //  purchase_request.ItemsSource = values.AsDataView();
                ExcelFileSelector fileS = new ExcelFileSelector();
                fileS.ShowDialog();
                values = DBManager.SelectFromExcel(fileS.fileName, fileS.sheetName, fileS.cellValues);

                purchase_request.ItemsSource = values.AsDataView();
            }
            catch
            {

            }

        }

        private void purchase_request_AutoGeneratedColumns(object sender, EventArgs e)
        {
            try
            {


                purchase_request.Columns[0].Header = "Group Id";
                purchase_request.Columns[1].Header = "Machine Id";
                purchase_request.Columns[2].Header = "Unit";
                purchase_request.Columns[3].Header = "Quantity";
                purchase_request.Columns[4].Header = "Site Id";
                purchase_request.Columns[5].Header = "Reason";
                purchase_request.Columns[6].Header = "Price";

                purchase_request.Columns[7].Header = "Remarks";


            }
            catch (Exception ex)
            {

                //this.Close();

            }
        }

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            if (values == null || values.Columns.Count != 8)
            {
                this.Close();
                myMessageBox mm = new myMessageBox("Invalid Columnns or Data", "Error", "OK", 1);
                mm.ShowDialog();

               // MessageBox.Show("Invalid Data size", "Error Occured", MessageBoxButton.OK, MessageBoxImage.Error);

            }
        }

        private void insertButton_Click(object sender, RoutedEventArgs e)
        {
            int i = 0;
            string datas = "";
            try
            {
                foreach (DataRow row in values.Rows)
                {
                    if (i == 0)
                    {
                        datas = "('" + row[0].ToString() + "','" + row[1].ToString() + "','" + row[2].ToString() + "','" + row[3].ToString() + "','" + row[4].ToString() + "','" + row[5].ToString() + "','" + row[6].ToString() + "')";

                    }
                    else
                    {
                        datas = datas + ",('" + row[0].ToString() + "','" + row[1].ToString() + "','" + row[2].ToString() + "','" + row[3].ToString() + "','" + row[4].ToString() + "','" + row[5].ToString() + "','" + row[6].ToString() + "')";
                    }
                    i++;
                }
                string res = DBManager.InsertIntoAllocationRequestes(datas);
                if (!res.Contains("Success"))
                {
                    myMessageBox mm = new myMessageBox("Invalid Data Type Found.Check your data again", "Error", "OK", 1);
                    mm.ShowDialog();

                   // MessageBox.Show("Invalid Data Type Found. Check your data again", "Error Occured", MessageBoxButton.OK, MessageBoxImage.Error);

                }
                else
                {
                    myMessageBox mm = new myMessageBox("Data Added Successfully", "Successfully Added", "OK", 0);
                    mm.ShowDialog();
                   // MessageBox.Show("Data Added Succesfully", "Successfully Added", MessageBoxButton.OK, MessageBoxImage.Information);
                    this.Close();
                }
            }
            catch (Exception ex)
            {
                //
            }
        }

    }
}